import type { NextPage } from 'next';
import Head from 'next/head'
import { useSession, signOut } from 'next-auth/react'
import Link from 'next/link';

export default function Home() {
  const { data } = useSession()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {data?.user?.name || <Link href="/auth/signin">Sign in</Link>} {""}
        {data?.user && <button onClick={() => signOut()}>Sign out</button>}</main>
    </>
  )
}
